/**
  ***********************************************************
  @file   /src/gpio/st/spec/STM32F446_gpio_v1_0.hpp
  @brief  This is autogenerated file        
  ***********************************************************
**/

#pragma once

//____________________INCLUDE_____________________//
#include <cstdint>
#include <type_traits>
#include "target.h"



namespace mpp::gpio
{
  inline namespace STM32F446_gpio_v1_0
  {
    enum class Port { 
      A = GPIOA_BASE,
      B = GPIOB_BASE,
      C = GPIOC_BASE,
      D = GPIOD_BASE,
      E = GPIOE_BASE,
      F = GPIOF_BASE,
      G = GPIOG_BASE,
      H = GPIOH_BASE,
    };

    constexpr bool IsValidPinId(Port port, std::uint32_t pin)
    {
      switch(port)
      { 
        case Port::A: return pin < 16u;
        case Port::B: return pin < 16u;
        case Port::C: return pin < 16u;
        case Port::D: return pin < 16u;
        case Port::E: return pin < 16u;
        case Port::F: return pin < 16u;
        case Port::G: return pin < 16u;
        case Port::H: return pin < 2u;

        default: return false;
      }
    }

    namespace Af 
    { 
      namespace PA0  { enum { TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  TIM5_CH1 = 2ul,  TIM8_ETR = 3ul,  UART4_TX = 8ul,  USART2_CTS = 7ul, }; }
      namespace PA1  { enum { QUADSPI_BK1_IO3 = 9ul,  SAI2_MCLK_B = 10ul,  TIM2_CH2 = 1ul,  TIM5_CH2 = 2ul,  UART4_RX = 8ul,  USART2_RTS = 7ul, }; }
      namespace PA10 { enum { DCMI_D1 = 13ul,  TIM1_CH3 = 1ul,  USART1_RX = 7ul,  USB_OTG_FS_ID = 10ul, }; }
      namespace PA11 { enum { CAN1_RX = 9ul,  TIM1_CH4 = 1ul,  USART1_CTS = 7ul,  USB_OTG_FS_DM = 10ul, }; }
      namespace PA12 { enum { CAN1_TX = 9ul,  SAI2_FS_B = 8ul,  TIM1_ETR = 1ul,  USART1_RTS = 7ul,  USB_OTG_FS_DP = 10ul, }; }
      namespace PA13 { enum { SYS_JTMS_SWDIO = 0ul, }; }
      namespace PA14 { enum { SYS_JTCK_SWCLK = 0ul, }; }
      namespace PA15 { enum { CEC = 4ul,  I2S1_WS = 5ul,  I2S3_WS = 6ul,  SPI1_NSS = 5ul,  SPI3_NSS = 6ul,  SYS_JTDI = 0ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  UART4_RTS = 8ul, }; }
      namespace PA2  { enum { SAI2_SCK_B = 8ul,  TIM2_CH3 = 1ul,  TIM5_CH3 = 2ul,  TIM9_CH1 = 3ul,  USART2_TX = 7ul, }; }
      namespace PA3  { enum { SAI1_FS_A = 6ul,  TIM2_CH4 = 1ul,  TIM5_CH4 = 2ul,  TIM9_CH2 = 3ul,  USART2_RX = 7ul,  USB_OTG_HS_ULPI_D0 = 10ul, }; }
      namespace PA4  { enum { DCMI_HSYNC = 13ul,  I2S1_WS = 5ul,  I2S3_WS = 6ul,  SPI1_NSS = 5ul,  SPI3_NSS = 6ul,  USART2_CK = 7ul,  USB_OTG_HS_SOF = 12ul, }; }
      namespace PA5  { enum { I2S1_CK = 5ul,  SPI1_SCK = 5ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  TIM8_CH1N = 3ul,  USB_OTG_HS_ULPI_CK = 10ul, }; }
      namespace PA6  { enum { DCMI_PIXCLK = 13ul,  I2S2_MCK = 6ul,  SPI1_MISO = 5ul,  TIM13_CH1 = 9ul,  TIM1_BKIN = 1ul,  TIM3_CH1 = 2ul,  TIM8_BKIN = 3ul, }; }
      namespace PA7  { enum { FMC_SDNWE = 12ul,  I2S1_SD = 5ul,  SPI1_MOSI = 5ul,  TIM14_CH1 = 9ul,  TIM1_CH1N = 1ul,  TIM3_CH2 = 2ul,  TIM8_CH1N = 3ul, }; }
      namespace PA8  { enum { I2C3_SCL = 4ul,  RCC_MCO_1 = 0ul,  TIM1_CH1 = 1ul,  USART1_CK = 7ul,  USB_OTG_FS_SOF = 10ul, }; }
      namespace PA9  { enum { DCMI_D0 = 13ul,  I2C3_SMBA = 4ul,  I2S2_CK = 5ul,  SAI1_SD_B = 6ul,  SPI2_SCK = 5ul,  TIM1_CH2 = 1ul,  USART1_TX = 7ul, }; }
      namespace PB0  { enum { I2S3_SD = 7ul,  SDIO_D1 = 12ul,  SPI3_MOSI = 7ul,  TIM1_CH2N = 1ul,  TIM3_CH3 = 2ul,  TIM8_CH2N = 3ul,  UART4_CTS = 8ul,  USB_OTG_HS_ULPI_D1 = 10ul, }; }
      namespace PB1  { enum { SDIO_D2 = 12ul,  TIM1_CH3N = 1ul,  TIM3_CH4 = 2ul,  TIM8_CH3N = 3ul,  USB_OTG_HS_ULPI_D2 = 10ul, }; }
      namespace PB10 { enum { I2C2_SCL = 4ul,  I2S2_CK = 5ul,  SAI1_SCK_A = 6ul,  SPI2_SCK = 5ul,  TIM2_CH3 = 1ul,  USART3_TX = 7ul,  USB_OTG_HS_ULPI_D3 = 10ul, }; }
      namespace PB11 { enum { I2C2_SDA = 4ul,  SAI2_SD_A = 8ul,  TIM2_CH4 = 1ul,  USART3_RX = 7ul,  USB_OTG_HS_ULPI_D4 = 10ul, }; }
      namespace PB12 { enum { CAN2_RX = 9ul,  I2C2_SMBA = 4ul,  I2S2_WS = 5ul,  SAI1_SCK_B = 6ul,  SPI2_NSS = 5ul,  TIM1_BKIN = 1ul,  USART3_CK = 7ul,  USB_OTG_HS_ID = 12ul,  USB_OTG_HS_ULPI_D5 = 10ul, }; }
      namespace PB13 { enum { CAN2_TX = 9ul,  I2S2_CK = 5ul,  SPI2_SCK = 5ul,  TIM1_CH1N = 1ul,  USART3_CTS = 7ul,  USB_OTG_HS_ULPI_D6 = 10ul, }; }
      namespace PB14 { enum { SPI2_MISO = 5ul,  TIM12_CH1 = 9ul,  TIM1_CH2N = 1ul,  TIM8_CH2N = 3ul,  USART3_RTS = 7ul,  USB_OTG_HS_DM = 12ul, }; }
      namespace PB15 { enum { I2S2_SD = 5ul,  RTC_REFIN = 0ul,  SPI2_MOSI = 5ul,  TIM12_CH2 = 9ul,  TIM1_CH3N = 1ul,  TIM8_CH3N = 3ul,  USB_OTG_HS_DP = 12ul, }; }
      namespace PB2  { enum { I2S3_SD = 7ul,  QUADSPI_CLK = 9ul,  SAI1_SD_A = 6ul,  SDIO_CK = 12ul,  SPI3_MOSI = 7ul,  TIM2_CH4 = 1ul,  USB_OTG_HS_ULPI_D4 = 10ul, }; }
      namespace PB3  { enum { I2C2_SDA = 4ul,  I2S1_CK = 5ul,  I2S3_CK = 6ul,  SPI1_SCK = 5ul,  SPI3_SCK = 6ul,  SYS_JTDO_SWO = 0ul,  TIM2_CH2 = 1ul, }; }
      namespace PB4  { enum { I2C3_SDA = 4ul,  I2S2_WS = 7ul,  SPI1_MISO = 5ul,  SPI2_NSS = 7ul,  SPI3_MISO = 6ul,  SYS_JTRST = 0ul,  TIM3_CH1 = 2ul, }; }
      namespace PB5  { enum { CAN2_RX = 9ul,  DCMI_D10 = 13ul,  FMC_SDCKE1 = 12ul,  I2C1_SMBA = 4ul,  I2S1_SD = 5ul,  I2S3_SD = 6ul,  SPI1_MOSI = 5ul,  SPI3_MOSI = 6ul,  TIM3_CH2 = 2ul,  USB_OTG_HS_ULPI_D7 = 10ul, }; }
      namespace PB6  { enum { CAN2_TX = 9ul,  CEC = 3ul,  DCMI_D5 = 13ul,  FMC_SDNE1 = 12ul,  I2C1_SCL = 4ul,  QUADSPI_BK1_NCS = 10ul,  TIM4_CH1 = 2ul,  USART1_TX = 7ul, }; }
      namespace PB7  { enum { DCMI_VSYNC = 13ul,  FMC_NL = 12ul,  I2C1_SDA = 4ul,  SPDIFRX_IN0 = 8ul,  TIM4_CH2 = 2ul,  USART1_RX = 7ul, }; }
      namespace PB8  { enum { CAN1_RX = 9ul,  DCMI_D6 = 13ul,  I2C1_SCL = 4ul,  SDIO_D4 = 12ul,  TIM10_CH1 = 3ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  TIM4_CH3 = 2ul, }; }
      namespace PB9  { enum { CAN1_TX = 9ul,  DCMI_D7 = 13ul,  I2C1_SDA = 4ul,  I2S2_WS = 5ul,  SAI1_FS_B = 6ul,  SDIO_D5 = 12ul,  SPI2_NSS = 5ul,  TIM11_CH1 = 3ul,  TIM2_CH2 = 1ul,  TIM4_CH4 = 2ul, }; }
      namespace PC0  { enum { FMC_SDNWE = 12ul,  SAI1_MCLK_B = 6ul,  USB_OTG_HS_ULPI_STP = 10ul, }; }
      namespace PC1  { enum { I2S2_SD = 7ul,  I2S3_SD = 5ul,  SAI1_SD_A = 6ul,  SPI2_MOSI = 7ul,  SPI3_MOSI = 5ul, }; }
      namespace PC10 { enum { DCMI_D8 = 13ul,  I2S3_CK = 6ul,  QUADSPI_BK1_IO1 = 9ul,  SDIO_D2 = 12ul,  SPI3_SCK = 6ul,  UART4_TX = 8ul,  USART3_TX = 7ul, }; }
      namespace PC11 { enum { DCMI_D4 = 13ul,  QUADSPI_BK2_NCS = 9ul,  SDIO_D3 = 12ul,  SPI3_MISO = 6ul,  UART4_RX = 8ul,  USART3_RX = 7ul, }; }
      namespace PC12 { enum { DCMI_D9 = 13ul,  I2C2_SDA = 4ul,  I2S3_SD = 6ul,  SDIO_CK = 12ul,  SPI3_MOSI = 6ul,  UART5_TX = 8ul,  USART3_CK = 7ul, }; }
      namespace PC13 { enum {}; }
      namespace PC14 { enum {}; }
      namespace PC15 { enum {}; }
      namespace PC2  { enum { FMC_SDNE0 = 12ul,  SPI2_MISO = 5ul,  USB_OTG_HS_ULPI_DIR = 10ul, }; }
      namespace PC3  { enum { FMC_SDCKE0 = 12ul,  I2S2_SD = 5ul,  SPI2_MOSI = 5ul,  USB_OTG_HS_ULPI_NXT = 10ul, }; }
      namespace PC4  { enum { FMC_SDNE0 = 12ul,  I2S1_MCK = 5ul,  SPDIFRX_IN2 = 8ul, }; }
      namespace PC5  { enum { FMC_SDCKE0 = 12ul,  SPDIFRX_IN3 = 8ul,  USART3_RX = 7ul, }; }
      namespace PC6  { enum { DCMI_D0 = 13ul,  FMPI2C1_SCL = 4ul,  I2S2_MCK = 5ul,  SDIO_D6 = 12ul,  TIM3_CH1 = 2ul,  TIM8_CH1 = 3ul,  USART6_TX = 8ul, }; }
      namespace PC7  { enum { DCMI_D1 = 13ul,  FMPI2C1_SDA = 4ul,  I2S2_CK = 5ul,  I2S3_MCK = 6ul,  SDIO_D7 = 12ul,  SPDIFRX_IN1 = 7ul,  SPI2_SCK = 5ul,  TIM3_CH2 = 2ul,  TIM8_CH2 = 3ul,  USART6_RX = 8ul, }; }
      namespace PC8  { enum { DCMI_D2 = 13ul,  SDIO_D0 = 12ul,  SYS_TRACED0 = 0ul,  TIM3_CH3 = 2ul,  TIM8_CH3 = 3ul,  UART5_RTS = 7ul,  USART6_CK = 8ul, }; }
      namespace PC9  { enum { DCMI_D3 = 13ul,  I2C3_SDA = 4ul,  I2S_CKIN = 5ul,  QUADSPI_BK1_IO0 = 9ul,  RCC_MCO_2 = 0ul,  SDIO_D1 = 12ul,  TIM3_CH4 = 2ul,  TIM8_CH4 = 3ul,  UART5_CTS = 7ul, }; }
      namespace PD0  { enum { CAN1_RX = 9ul,  FMC_D2 = 12ul,  FMC_DA2 = 12ul,  I2S3_SD = 6ul,  SPI3_MOSI = 6ul,  SPI4_MISO = 5ul, }; }
      namespace PD1  { enum { CAN1_TX = 9ul,  FMC_D3 = 12ul,  FMC_DA3 = 12ul,  I2S2_WS = 7ul,  SPI2_NSS = 7ul, }; }
      namespace PD10 { enum { FMC_D15 = 12ul,  FMC_DA15 = 12ul,  USART3_CK = 7ul, }; }
      namespace PD11 { enum { FMC_A16 = 12ul,  FMPI2C1_SMBA = 4ul,  QUADSPI_BK1_IO0 = 9ul,  SAI2_SD_A = 10ul,  USART3_CTS = 7ul, }; }
      namespace PD12 { enum { FMC_A17 = 12ul,  FMPI2C1_SCL = 4ul,  QUADSPI_BK1_IO1 = 9ul,  SAI2_FS_A = 10ul,  TIM4_CH1 = 2ul,  USART3_RTS = 7ul, }; }
      namespace PD13 { enum { FMC_A18 = 12ul,  FMPI2C1_SDA = 4ul,  QUADSPI_BK1_IO3 = 9ul,  SAI2_SCK_A = 10ul,  TIM4_CH2 = 2ul, }; }
      namespace PD14 { enum { FMC_D0 = 12ul,  FMC_DA0 = 12ul,  FMPI2C1_SCL = 4ul,  SAI2_SCK_A = 8ul,  TIM4_CH3 = 2ul, }; }
      namespace PD15 { enum { FMC_D1 = 12ul,  FMC_DA1 = 12ul,  FMPI2C1_SDA = 4ul,  TIM4_CH4 = 2ul, }; }
      namespace PD2  { enum { DCMI_D11 = 13ul,  SDIO_CMD = 12ul,  TIM3_ETR = 2ul,  UART5_RX = 8ul, }; }
      namespace PD3  { enum { DCMI_D5 = 13ul,  FMC_CLK = 12ul,  I2S2_CK = 5ul,  QUADSPI_CLK = 9ul,  SPI2_SCK = 5ul,  SYS_TRACED1 = 0ul,  USART2_CTS = 7ul, }; }
      namespace PD4  { enum { FMC_NOE = 12ul,  USART2_RTS = 7ul, }; }
      namespace PD5  { enum { FMC_NWE = 12ul,  USART2_TX = 7ul, }; }
      namespace PD6  { enum { DCMI_D10 = 13ul,  FMC_NWAIT = 12ul,  I2S3_SD = 5ul,  SAI1_SD_A = 6ul,  SPI3_MOSI = 5ul,  USART2_RX = 7ul, }; }
      namespace PD7  { enum { FMC_NE1 = 12ul,  SPDIFRX_IN0 = 8ul,  USART2_CK = 7ul, }; }
      namespace PD8  { enum { FMC_D13 = 12ul,  FMC_DA13 = 12ul,  SPDIFRX_IN1 = 8ul,  USART3_TX = 7ul, }; }
      namespace PD9  { enum { FMC_D14 = 12ul,  FMC_DA14 = 12ul,  USART3_RX = 7ul, }; }
      namespace PE0  { enum { DCMI_D2 = 13ul,  FMC_NBL0 = 12ul,  SAI2_MCLK_A = 10ul,  TIM4_ETR = 2ul, }; }
      namespace PE1  { enum { DCMI_D3 = 13ul,  FMC_NBL1 = 12ul, }; }
      namespace PE10 { enum { FMC_D7 = 12ul,  FMC_DA7 = 12ul,  QUADSPI_BK2_IO3 = 10ul,  TIM1_CH2N = 1ul, }; }
      namespace PE11 { enum { FMC_D8 = 12ul,  FMC_DA8 = 12ul,  SAI2_SD_B = 10ul,  SPI4_NSS = 5ul,  TIM1_CH2 = 1ul, }; }
      namespace PE12 { enum { FMC_D9 = 12ul,  FMC_DA9 = 12ul,  SAI2_SCK_B = 10ul,  SPI4_SCK = 5ul,  TIM1_CH3N = 1ul, }; }
      namespace PE13 { enum { FMC_D10 = 12ul,  FMC_DA10 = 12ul,  SAI2_FS_B = 10ul,  SPI4_MISO = 5ul,  TIM1_CH3 = 1ul, }; }
      namespace PE14 { enum { FMC_D11 = 12ul,  FMC_DA11 = 12ul,  SAI2_MCLK_B = 10ul,  SPI4_MOSI = 5ul,  TIM1_CH4 = 1ul, }; }
      namespace PE15 { enum { FMC_D12 = 12ul,  FMC_DA12 = 12ul,  TIM1_BKIN = 1ul, }; }
      namespace PE2  { enum { FMC_A23 = 12ul,  QUADSPI_BK1_IO2 = 9ul,  SAI1_MCLK_A = 6ul,  SPI4_SCK = 5ul,  SYS_TRACECLK = 0ul, }; }
      namespace PE3  { enum { FMC_A19 = 12ul,  SAI1_SD_B = 6ul,  SYS_TRACED0 = 0ul, }; }
      namespace PE4  { enum { DCMI_D4 = 13ul,  FMC_A20 = 12ul,  SAI1_FS_A = 6ul,  SPI4_NSS = 5ul,  SYS_TRACED1 = 0ul, }; }
      namespace PE5  { enum { DCMI_D6 = 13ul,  FMC_A21 = 12ul,  SAI1_SCK_A = 6ul,  SPI4_MISO = 5ul,  SYS_TRACED2 = 0ul,  TIM9_CH1 = 3ul, }; }
      namespace PE6  { enum { DCMI_D7 = 13ul,  FMC_A22 = 12ul,  SAI1_SD_A = 6ul,  SPI4_MOSI = 5ul,  SYS_TRACED3 = 0ul,  TIM9_CH2 = 3ul, }; }
      namespace PE7  { enum { FMC_D4 = 12ul,  FMC_DA4 = 12ul,  QUADSPI_BK2_IO0 = 10ul,  TIM1_ETR = 1ul,  UART5_RX = 8ul, }; }
      namespace PE8  { enum { FMC_D5 = 12ul,  FMC_DA5 = 12ul,  QUADSPI_BK2_IO1 = 10ul,  TIM1_CH1N = 1ul,  UART5_TX = 8ul, }; }
      namespace PE9  { enum { FMC_D6 = 12ul,  FMC_DA6 = 12ul,  QUADSPI_BK2_IO2 = 10ul,  TIM1_CH1 = 1ul, }; }
      namespace PF0  { enum { FMC_A0 = 12ul,  I2C2_SDA = 4ul, }; }
      namespace PF1  { enum { FMC_A1 = 12ul,  I2C2_SCL = 4ul, }; }
      namespace PF10 { enum { DCMI_D11 = 13ul, }; }
      namespace PF11 { enum { DCMI_D12 = 13ul,  FMC_SDNRAS = 12ul,  SAI2_SD_B = 10ul, }; }
      namespace PF12 { enum { FMC_A6 = 12ul, }; }
      namespace PF13 { enum { FMC_A7 = 12ul,  FMPI2C1_SMBA = 4ul, }; }
      namespace PF14 { enum { FMC_A8 = 12ul,  FMPI2C1_SCL = 4ul, }; }
      namespace PF15 { enum { FMC_A9 = 12ul,  FMPI2C1_SDA = 4ul, }; }
      namespace PF2  { enum { FMC_A2 = 12ul,  I2C2_SMBA = 4ul, }; }
      namespace PF3  { enum { FMC_A3 = 12ul, }; }
      namespace PF4  { enum { FMC_A4 = 12ul, }; }
      namespace PF5  { enum { FMC_A5 = 12ul, }; }
      namespace PF6  { enum { QUADSPI_BK1_IO3 = 9ul,  SAI1_SD_B = 6ul,  TIM10_CH1 = 3ul, }; }
      namespace PF7  { enum { QUADSPI_BK1_IO2 = 9ul,  SAI1_MCLK_B = 6ul,  TIM11_CH1 = 3ul, }; }
      namespace PF8  { enum { QUADSPI_BK1_IO0 = 10ul,  SAI1_SCK_B = 6ul,  TIM13_CH1 = 9ul, }; }
      namespace PF9  { enum { QUADSPI_BK1_IO1 = 10ul,  SAI1_FS_B = 6ul,  TIM14_CH1 = 9ul, }; }
      namespace PG0  { enum { FMC_A10 = 12ul, }; }
      namespace PG1  { enum { FMC_A11 = 12ul, }; }
      namespace PG10 { enum { DCMI_D2 = 13ul,  FMC_NE3 = 12ul,  SAI2_SD_B = 10ul, }; }
      namespace PG11 { enum { DCMI_D3 = 13ul,  SPDIFRX_IN0 = 7ul,  SPI4_SCK = 6ul, }; }
      namespace PG12 { enum { FMC_NE4 = 12ul,  SPDIFRX_IN1 = 7ul,  SPI4_MISO = 6ul,  USART6_RTS = 8ul, }; }
      namespace PG13 { enum { FMC_A24 = 12ul,  SPI4_MOSI = 6ul,  SYS_TRACED2 = 0ul,  USART6_CTS = 8ul, }; }
      namespace PG14 { enum { FMC_A25 = 12ul,  QUADSPI_BK2_IO3 = 9ul,  SPI4_NSS = 6ul,  SYS_TRACED3 = 0ul,  USART6_TX = 8ul, }; }
      namespace PG15 { enum { DCMI_D13 = 13ul,  FMC_SDNCAS = 12ul,  USART6_CTS = 8ul, }; }
      namespace PG2  { enum { FMC_A12 = 12ul, }; }
      namespace PG3  { enum { FMC_A13 = 12ul, }; }
      namespace PG4  { enum { FMC_A14 = 12ul,  FMC_BA0 = 12ul, }; }
      namespace PG5  { enum { FMC_A15 = 12ul,  FMC_BA1 = 12ul, }; }
      namespace PG6  { enum { DCMI_D12 = 13ul,  QUADSPI_BK1_NCS = 10ul, }; }
      namespace PG7  { enum { DCMI_D13 = 13ul,  FMC_INT3 = 12ul,  USART6_CK = 8ul, }; }
      namespace PG8  { enum { FMC_SDCLK = 12ul,  SPDIFRX_IN2 = 7ul,  USART6_RTS = 8ul, }; }
      namespace PG9  { enum { DCMI_VSYNC = 13ul,  FMC_NCE3 = 12ul,  FMC_NE2 = 12ul,  QUADSPI_BK2_IO2 = 9ul,  SAI2_FS_B = 10ul,  SPDIFRX_IN3 = 7ul,  USART6_RX = 8ul, }; }
      namespace PH0  { enum {}; }
      namespace PH1  { enum {}; }
    } // namespace Af
  } // inline namespace gpio401
} // namespace mpp::gpio 
 
