/**
  ***********************************************************
  @file   /src/gpio/st/spec/STM32F412_gpio_v1_0.hpp
  @brief  This is autogenerated file        
  ***********************************************************
**/

#pragma once

//____________________INCLUDE_____________________//
#include <cstdint>


#if defined (STM32F412cx)
  #include "stm32f412cx.h"
#elif defined (STM32F412rx)
  #include "stm32f412rx.h"
#elif defined (STM32F412vx)
  #include "stm32f412vx.h"
#elif defined (STM32F412zx)
  #include "stm32f412zx.h"
#else
  #error "You must define supported target"
#endif



namespace mpp::gpio
{
  inline namespace STM32F412_gpio_v1_0
  {
    enum class Port { 
      A = GPIOA_BASE,
      B = GPIOB_BASE,
      C = GPIOC_BASE,
      D = GPIOD_BASE,
      E = GPIOE_BASE,
      F = GPIOF_BASE,
      G = GPIOG_BASE,
      H = GPIOH_BASE,
    };

    constexpr bool IsValidPinId(Port port, std::uint32_t pin)
    {
      switch(port)
      { 
        case Port::A: return pin < 16u;
        case Port::B: return pin < 16u;
        case Port::C: return pin < 16u;
        case Port::D: return pin < 16u;
        case Port::E: return pin < 16u;
        case Port::F: return pin < 16u;
        case Port::G: return pin < 16u;
        case Port::H: return pin < 2u;

        default: return false;
      }
    }

    namespace Af 
    { 
      namespace PA0  { enum { EVENTOUT = 15ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  TIM5_CH1 = 2ul,  TIM8_ETR = 3ul,  USART2_CTS = 7ul, }; }
      namespace PA1  { enum { EVENTOUT = 15ul,  I2S4_SD = 5ul,  QUADSPI_BK1_IO3 = 9ul,  SPI4_MOSI = 5ul,  TIM2_CH2 = 1ul,  TIM5_CH2 = 2ul,  USART2_RTS = 7ul, }; }
      namespace PA10 { enum { EVENTOUT = 15ul,  I2S5_SD = 6ul,  SPI5_MOSI = 6ul,  TIM1_CH3 = 1ul,  USART1_RX = 7ul,  USB_OTG_FS_ID = 10ul, }; }
      namespace PA11 { enum { CAN1_RX = 9ul,  EVENTOUT = 15ul,  SPI4_MISO = 6ul,  TIM1_CH4 = 1ul,  USART1_CTS = 7ul,  USART6_TX = 8ul,  USB_OTG_FS_DM = 10ul, }; }
      namespace PA12 { enum { CAN1_TX = 9ul,  EVENTOUT = 15ul,  SPI5_MISO = 6ul,  TIM1_ETR = 1ul,  USART1_RTS = 7ul,  USART6_RX = 8ul,  USB_OTG_FS_DP = 10ul, }; }
      namespace PA13 { enum { EVENTOUT = 15ul,  SYS_JTMS_SWDIO = 0ul, }; }
      namespace PA14 { enum { EVENTOUT = 15ul,  SYS_JTCK_SWCLK = 0ul, }; }
      namespace PA15 { enum { EVENTOUT = 15ul,  I2S1_WS = 5ul,  I2S3_WS = 6ul,  SPI1_NSS = 5ul,  SPI3_NSS = 6ul,  SYS_JTDI = 0ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  USART1_TX = 7ul, }; }
      namespace PA2  { enum { EVENTOUT = 15ul,  FSMC_D4 = 12ul,  FSMC_DA4 = 12ul,  I2S_CKIN = 5ul,  TIM2_CH3 = 1ul,  TIM5_CH3 = 2ul,  TIM9_CH1 = 3ul,  USART2_TX = 7ul, }; }
      namespace PA3  { enum { EVENTOUT = 15ul,  FSMC_D5 = 12ul,  FSMC_DA5 = 12ul,  I2S2_MCK = 5ul,  TIM2_CH4 = 1ul,  TIM5_CH4 = 2ul,  TIM9_CH2 = 3ul,  USART2_RX = 7ul, }; }
      namespace PA4  { enum { DFSDM1_DATIN1 = 8ul,  EVENTOUT = 15ul,  FSMC_D6 = 12ul,  FSMC_DA6 = 12ul,  I2S1_WS = 5ul,  I2S3_WS = 6ul,  SPI1_NSS = 5ul,  SPI3_NSS = 6ul,  USART2_CK = 7ul, }; }
      namespace PA5  { enum { DFSDM1_CKIN1 = 8ul,  EVENTOUT = 15ul,  FSMC_D7 = 12ul,  FSMC_DA7 = 12ul,  I2S1_CK = 5ul,  SPI1_SCK = 5ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  TIM8_CH1N = 3ul, }; }
      namespace PA6  { enum { EVENTOUT = 15ul,  I2S2_MCK = 6ul,  QUADSPI_BK2_IO0 = 10ul,  SDIO_CMD = 12ul,  SPI1_MISO = 5ul,  TIM13_CH1 = 9ul,  TIM1_BKIN = 1ul,  TIM3_CH1 = 2ul,  TIM8_BKIN = 3ul, }; }
      namespace PA7  { enum { EVENTOUT = 15ul,  I2S1_SD = 5ul,  QUADSPI_BK2_IO1 = 10ul,  SPI1_MOSI = 5ul,  TIM14_CH1 = 9ul,  TIM1_CH1N = 1ul,  TIM3_CH2 = 2ul,  TIM8_CH1N = 3ul, }; }
      namespace PA8  { enum { EVENTOUT = 15ul,  I2C3_SCL = 4ul,  RCC_MCO_1 = 0ul,  SDIO_D1 = 12ul,  TIM1_CH1 = 1ul,  USART1_CK = 7ul,  USB_OTG_FS_SOF = 10ul, }; }
      namespace PA9  { enum { EVENTOUT = 15ul,  I2C3_SMBA = 4ul,  SDIO_D2 = 12ul,  TIM1_CH2 = 1ul,  USART1_TX = 7ul,  USB_OTG_FS_VBUS = 10ul, }; }
      namespace PB0  { enum { EVENTOUT = 15ul,  I2S5_CK = 6ul,  SPI5_SCK = 6ul,  TIM1_CH2N = 1ul,  TIM3_CH3 = 2ul,  TIM8_CH2N = 3ul, }; }
      namespace PB1  { enum { DFSDM1_DATIN0 = 8ul,  EVENTOUT = 15ul,  I2S5_WS = 6ul,  QUADSPI_CLK = 9ul,  SPI5_NSS = 6ul,  TIM1_CH3N = 1ul,  TIM3_CH4 = 2ul,  TIM8_CH3N = 3ul, }; }
      namespace PB10 { enum { EVENTOUT = 15ul,  FMPI2C1_SCL = 9ul,  I2C2_SCL = 4ul,  I2S2_CK = 5ul,  I2S3_MCK = 6ul,  SDIO_D7 = 12ul,  SPI2_SCK = 5ul,  TIM2_CH3 = 1ul,  USART3_TX = 7ul, }; }
      namespace PB11 { enum { EVENTOUT = 15ul,  I2C2_SDA = 4ul,  I2S_CKIN = 5ul,  TIM2_CH4 = 1ul,  USART3_RX = 7ul, }; }
      namespace PB12 { enum { CAN2_RX = 9ul,  DFSDM1_DATIN1 = 10ul,  EVENTOUT = 15ul,  FSMC_D13 = 12ul,  FSMC_DA13 = 12ul,  I2C2_SMBA = 4ul,  I2S2_WS = 5ul,  I2S3_CK = 7ul,  I2S4_WS = 6ul,  SPI2_NSS = 5ul,  SPI3_SCK = 7ul,  SPI4_NSS = 6ul,  TIM1_BKIN = 1ul,  USART3_CK = 8ul, }; }
      namespace PB13 { enum { CAN2_TX = 9ul,  DFSDM1_CKIN1 = 10ul,  EVENTOUT = 15ul,  FMPI2C1_SMBA = 4ul,  I2S2_CK = 5ul,  I2S4_CK = 6ul,  SPI2_SCK = 5ul,  SPI4_SCK = 6ul,  TIM1_CH1N = 1ul,  USART3_CTS = 8ul, }; }
      namespace PB14 { enum { DFSDM1_DATIN2 = 8ul,  EVENTOUT = 15ul,  FMPI2C1_SDA = 4ul,  FSMC_D0 = 10ul,  FSMC_DA0 = 10ul,  I2S2_ext_SD = 6ul,  SDIO_D6 = 12ul,  SPI2_MISO = 5ul,  TIM12_CH1 = 9ul,  TIM1_CH2N = 1ul,  TIM8_CH2N = 3ul,  USART3_RTS = 7ul, }; }
      namespace PB15 { enum { DFSDM1_CKIN2 = 8ul,  EVENTOUT = 15ul,  FMPI2C1_SCL = 4ul,  I2S2_SD = 5ul,  RTC_REFIN = 0ul,  SDIO_CK = 12ul,  SPI2_MOSI = 5ul,  TIM12_CH2 = 9ul,  TIM1_CH3N = 1ul,  TIM8_CH3N = 3ul, }; }
      namespace PB2  { enum { DFSDM1_CKIN0 = 6ul,  EVENTOUT = 15ul,  QUADSPI_CLK = 9ul, }; }
      namespace PB3  { enum { EVENTOUT = 15ul,  FMPI2C1_SDA = 4ul,  I2C2_SDA = 9ul,  I2S1_CK = 5ul,  I2S3_CK = 6ul,  SPI1_SCK = 5ul,  SPI3_SCK = 6ul,  SYS_JTDO_SWO = 0ul,  TIM2_CH2 = 1ul,  USART1_RX = 7ul, }; }
      namespace PB4  { enum { EVENTOUT = 15ul,  I2C3_SDA = 9ul,  I2S3_ext_SD = 7ul,  SDIO_D0 = 12ul,  SPI1_MISO = 5ul,  SPI3_MISO = 6ul,  SYS_JTRST = 0ul,  TIM3_CH1 = 2ul, }; }
      namespace PB5  { enum { CAN2_RX = 9ul,  EVENTOUT = 15ul,  I2C1_SMBA = 4ul,  I2S1_SD = 5ul,  I2S3_SD = 6ul,  SDIO_D3 = 12ul,  SPI1_MOSI = 5ul,  SPI3_MOSI = 6ul,  TIM3_CH2 = 2ul, }; }
      namespace PB6  { enum { CAN2_TX = 9ul,  EVENTOUT = 15ul,  I2C1_SCL = 4ul,  QUADSPI_BK1_NCS = 10ul,  SDIO_D0 = 12ul,  TIM4_CH1 = 2ul,  USART1_TX = 7ul, }; }
      namespace PB7  { enum { EVENTOUT = 15ul,  FSMC_NL = 12ul,  I2C1_SDA = 4ul,  TIM4_CH2 = 2ul,  USART1_RX = 7ul, }; }
      namespace PB8  { enum { CAN1_RX = 8ul,  EVENTOUT = 15ul,  I2C1_SCL = 4ul,  I2C3_SDA = 9ul,  I2S5_SD = 6ul,  SDIO_D4 = 12ul,  SPI5_MOSI = 6ul,  TIM10_CH1 = 3ul,  TIM4_CH3 = 2ul, }; }
      namespace PB9  { enum { CAN1_TX = 8ul,  EVENTOUT = 15ul,  I2C1_SDA = 4ul,  I2C2_SDA = 9ul,  I2S2_WS = 5ul,  SDIO_D5 = 12ul,  SPI2_NSS = 5ul,  TIM11_CH1 = 3ul,  TIM4_CH4 = 2ul, }; }
      namespace PC0  { enum { EVENTOUT = 15ul, }; }
      namespace PC1  { enum { EVENTOUT = 15ul, }; }
      namespace PC10 { enum { EVENTOUT = 15ul,  I2S3_CK = 6ul,  QUADSPI_BK1_IO1 = 9ul,  SDIO_D2 = 12ul,  SPI3_SCK = 6ul,  USART3_TX = 7ul, }; }
      namespace PC11 { enum { EVENTOUT = 15ul,  FSMC_D2 = 10ul,  FSMC_DA2 = 10ul,  I2S3_ext_SD = 5ul,  QUADSPI_BK2_NCS = 9ul,  SDIO_D3 = 12ul,  SPI3_MISO = 6ul,  USART3_RX = 7ul, }; }
      namespace PC12 { enum { EVENTOUT = 15ul,  FSMC_D3 = 10ul,  FSMC_DA3 = 10ul,  I2S3_SD = 6ul,  SDIO_CK = 12ul,  SPI3_MOSI = 6ul,  USART3_CK = 7ul, }; }
      namespace PC13 { enum { EVENTOUT = 15ul, }; }
      namespace PC14 { enum { EVENTOUT = 15ul, }; }
      namespace PC15 { enum { EVENTOUT = 15ul, }; }
      namespace PC2  { enum { DFSDM1_CKOUT = 8ul,  EVENTOUT = 15ul,  FSMC_NWE = 12ul,  I2S2_ext_SD = 6ul,  SPI2_MISO = 5ul, }; }
      namespace PC3  { enum { EVENTOUT = 15ul,  FSMC_A0 = 12ul,  I2S2_SD = 5ul,  SPI2_MOSI = 5ul, }; }
      namespace PC4  { enum { EVENTOUT = 15ul,  FSMC_NE4 = 12ul,  I2S1_MCK = 5ul,  QUADSPI_BK2_IO2 = 10ul, }; }
      namespace PC5  { enum { EVENTOUT = 15ul,  FMPI2C1_SMBA = 4ul,  FSMC_NOE = 12ul,  QUADSPI_BK2_IO3 = 10ul,  USART3_RX = 7ul, }; }
      namespace PC6  { enum { DFSDM1_CKIN3 = 6ul,  EVENTOUT = 15ul,  FMPI2C1_SCL = 4ul,  FSMC_D1 = 10ul,  FSMC_DA1 = 10ul,  I2S2_MCK = 5ul,  SDIO_D6 = 12ul,  TIM3_CH1 = 2ul,  TIM8_CH1 = 3ul,  USART6_TX = 8ul, }; }
      namespace PC7  { enum { DFSDM1_DATIN3 = 10ul,  EVENTOUT = 15ul,  FMPI2C1_SDA = 4ul,  I2S2_CK = 5ul,  I2S3_MCK = 6ul,  SDIO_D7 = 12ul,  SPI2_SCK = 5ul,  TIM3_CH2 = 2ul,  TIM8_CH2 = 3ul,  USART6_RX = 8ul, }; }
      namespace PC8  { enum { EVENTOUT = 15ul,  QUADSPI_BK1_IO2 = 9ul,  SDIO_D0 = 12ul,  TIM3_CH3 = 2ul,  TIM8_CH3 = 3ul,  USART6_CK = 8ul, }; }
      namespace PC9  { enum { EVENTOUT = 15ul,  I2C3_SDA = 4ul,  I2S_CKIN = 5ul,  QUADSPI_BK1_IO0 = 9ul,  RCC_MCO_2 = 0ul,  SDIO_D1 = 12ul,  TIM3_CH4 = 2ul,  TIM8_CH4 = 3ul, }; }
      namespace PD0  { enum { CAN1_RX = 9ul,  EVENTOUT = 15ul,  FSMC_D2 = 12ul,  FSMC_DA2 = 12ul, }; }
      namespace PD1  { enum { CAN1_TX = 9ul,  EVENTOUT = 15ul,  FSMC_D3 = 12ul,  FSMC_DA3 = 12ul, }; }
      namespace PD10 { enum { EVENTOUT = 15ul,  FSMC_D15 = 12ul,  FSMC_DA15 = 12ul,  USART3_CK = 7ul, }; }
      namespace PD11 { enum { EVENTOUT = 15ul,  FMPI2C1_SMBA = 4ul,  FSMC_A16 = 12ul,  QUADSPI_BK1_IO0 = 9ul,  USART3_CTS = 7ul, }; }
      namespace PD12 { enum { EVENTOUT = 15ul,  FMPI2C1_SCL = 4ul,  FSMC_A17 = 12ul,  QUADSPI_BK1_IO1 = 9ul,  TIM4_CH1 = 2ul,  USART3_RTS = 7ul, }; }
      namespace PD13 { enum { EVENTOUT = 15ul,  FMPI2C1_SDA = 4ul,  FSMC_A18 = 12ul,  QUADSPI_BK1_IO3 = 9ul,  TIM4_CH2 = 2ul, }; }
      namespace PD14 { enum { EVENTOUT = 15ul,  FMPI2C1_SCL = 4ul,  FSMC_D0 = 12ul,  FSMC_DA0 = 12ul,  TIM4_CH3 = 2ul, }; }
      namespace PD15 { enum { EVENTOUT = 15ul,  FMPI2C1_SDA = 4ul,  FSMC_D1 = 12ul,  FSMC_DA1 = 12ul,  TIM4_CH4 = 2ul, }; }
      namespace PD2  { enum { EVENTOUT = 15ul,  FSMC_NWE = 10ul,  SDIO_CMD = 12ul,  TIM3_ETR = 2ul, }; }
      namespace PD3  { enum { DFSDM1_DATIN0 = 6ul,  EVENTOUT = 15ul,  FSMC_CLK = 12ul,  I2S2_CK = 5ul,  QUADSPI_CLK = 9ul,  SPI2_SCK = 5ul,  SYS_TRACED1 = 0ul,  USART2_CTS = 7ul, }; }
      namespace PD4  { enum { DFSDM1_CKIN0 = 6ul,  EVENTOUT = 15ul,  FSMC_NOE = 12ul,  USART2_RTS = 7ul, }; }
      namespace PD5  { enum { EVENTOUT = 15ul,  FSMC_NWE = 12ul,  USART2_TX = 7ul, }; }
      namespace PD6  { enum { DFSDM1_DATIN1 = 6ul,  EVENTOUT = 15ul,  FSMC_NWAIT = 12ul,  I2S3_SD = 5ul,  SPI3_MOSI = 5ul,  USART2_RX = 7ul, }; }
      namespace PD7  { enum { DFSDM1_CKIN1 = 6ul,  EVENTOUT = 15ul,  FSMC_NE1 = 12ul,  USART2_CK = 7ul, }; }
      namespace PD8  { enum { EVENTOUT = 15ul,  FSMC_D13 = 12ul,  FSMC_DA13 = 12ul,  USART3_TX = 7ul, }; }
      namespace PD9  { enum { EVENTOUT = 15ul,  FSMC_D14 = 12ul,  FSMC_DA14 = 12ul,  USART3_RX = 7ul, }; }
      namespace PE0  { enum { EVENTOUT = 15ul,  FSMC_NBL0 = 12ul,  TIM4_ETR = 2ul, }; }
      namespace PE1  { enum { EVENTOUT = 15ul,  FSMC_NBL1 = 12ul, }; }
      namespace PE10 { enum { EVENTOUT = 15ul,  FSMC_D7 = 12ul,  FSMC_DA7 = 12ul,  QUADSPI_BK2_IO3 = 10ul,  TIM1_CH2N = 1ul, }; }
      namespace PE11 { enum { EVENTOUT = 15ul,  FSMC_D8 = 12ul,  FSMC_DA8 = 12ul,  I2S4_WS = 5ul,  I2S5_WS = 6ul,  SPI4_NSS = 5ul,  SPI5_NSS = 6ul,  TIM1_CH2 = 1ul, }; }
      namespace PE12 { enum { EVENTOUT = 15ul,  FSMC_D9 = 12ul,  FSMC_DA9 = 12ul,  I2S4_CK = 5ul,  I2S5_CK = 6ul,  SPI4_SCK = 5ul,  SPI5_SCK = 6ul,  TIM1_CH3N = 1ul, }; }
      namespace PE13 { enum { EVENTOUT = 15ul,  FSMC_D10 = 12ul,  FSMC_DA10 = 12ul,  SPI4_MISO = 5ul,  SPI5_MISO = 6ul,  TIM1_CH3 = 1ul, }; }
      namespace PE14 { enum { EVENTOUT = 15ul,  FSMC_D11 = 12ul,  FSMC_DA11 = 12ul,  I2S4_SD = 5ul,  I2S5_SD = 6ul,  SPI4_MOSI = 5ul,  SPI5_MOSI = 6ul,  TIM1_CH4 = 1ul, }; }
      namespace PE15 { enum { EVENTOUT = 15ul,  FSMC_D12 = 12ul,  FSMC_DA12 = 12ul,  TIM1_BKIN = 1ul, }; }
      namespace PE2  { enum { EVENTOUT = 15ul,  FSMC_A23 = 12ul,  I2S4_CK = 5ul,  I2S5_CK = 6ul,  QUADSPI_BK1_IO2 = 9ul,  SPI4_SCK = 5ul,  SPI5_SCK = 6ul,  SYS_TRACECLK = 0ul, }; }
      namespace PE3  { enum { EVENTOUT = 15ul,  FSMC_A19 = 12ul,  SYS_TRACED0 = 0ul, }; }
      namespace PE4  { enum { DFSDM1_DATIN3 = 8ul,  EVENTOUT = 15ul,  FSMC_A20 = 12ul,  I2S4_WS = 5ul,  I2S5_WS = 6ul,  SPI4_NSS = 5ul,  SPI5_NSS = 6ul,  SYS_TRACED1 = 0ul, }; }
      namespace PE5  { enum { DFSDM1_CKIN3 = 8ul,  EVENTOUT = 15ul,  FSMC_A21 = 12ul,  SPI4_MISO = 5ul,  SPI5_MISO = 6ul,  SYS_TRACED2 = 0ul,  TIM9_CH1 = 3ul, }; }
      namespace PE6  { enum { EVENTOUT = 15ul,  FSMC_A22 = 12ul,  I2S4_SD = 5ul,  I2S5_SD = 6ul,  SPI4_MOSI = 5ul,  SPI5_MOSI = 6ul,  SYS_TRACED3 = 0ul,  TIM9_CH2 = 3ul, }; }
      namespace PE7  { enum { DFSDM1_DATIN2 = 6ul,  EVENTOUT = 15ul,  FSMC_D4 = 12ul,  FSMC_DA4 = 12ul,  QUADSPI_BK2_IO0 = 10ul,  TIM1_ETR = 1ul, }; }
      namespace PE8  { enum { DFSDM1_CKIN2 = 6ul,  EVENTOUT = 15ul,  FSMC_D5 = 12ul,  FSMC_DA5 = 12ul,  QUADSPI_BK2_IO1 = 10ul,  TIM1_CH1N = 1ul, }; }
      namespace PE9  { enum { DFSDM1_CKOUT = 6ul,  EVENTOUT = 15ul,  FSMC_D6 = 12ul,  FSMC_DA6 = 12ul,  QUADSPI_BK2_IO2 = 10ul,  TIM1_CH1 = 1ul, }; }
      namespace PF0  { enum { EVENTOUT = 15ul,  FSMC_A0 = 12ul,  I2C2_SDA = 4ul, }; }
      namespace PF1  { enum { EVENTOUT = 15ul,  FSMC_A1 = 12ul,  I2C2_SCL = 4ul, }; }
      namespace PF10 { enum { EVENTOUT = 15ul,  TIM1_ETR = 1ul,  TIM5_CH4 = 2ul, }; }
      namespace PF11 { enum { EVENTOUT = 15ul,  TIM8_ETR = 3ul, }; }
      namespace PF12 { enum { EVENTOUT = 15ul,  FSMC_A6 = 12ul,  TIM8_BKIN = 3ul, }; }
      namespace PF13 { enum { EVENTOUT = 15ul,  FMPI2C1_SMBA = 4ul,  FSMC_A7 = 12ul, }; }
      namespace PF14 { enum { EVENTOUT = 15ul,  FMPI2C1_SCL = 4ul,  FSMC_A8 = 12ul, }; }
      namespace PF15 { enum { EVENTOUT = 15ul,  FMPI2C1_SDA = 4ul,  FSMC_A9 = 12ul, }; }
      namespace PF2  { enum { EVENTOUT = 15ul,  FSMC_A2 = 12ul,  I2C2_SMBA = 4ul, }; }
      namespace PF3  { enum { EVENTOUT = 15ul,  FSMC_A3 = 12ul,  TIM5_CH1 = 2ul, }; }
      namespace PF4  { enum { EVENTOUT = 15ul,  FSMC_A4 = 12ul,  TIM5_CH2 = 2ul, }; }
      namespace PF5  { enum { EVENTOUT = 15ul,  FSMC_A5 = 12ul,  TIM5_CH3 = 2ul, }; }
      namespace PF6  { enum { EVENTOUT = 15ul,  QUADSPI_BK1_IO3 = 9ul,  SYS_TRACED0 = 0ul,  TIM10_CH1 = 3ul, }; }
      namespace PF7  { enum { EVENTOUT = 15ul,  QUADSPI_BK1_IO2 = 9ul,  SYS_TRACED1 = 0ul,  TIM11_CH1 = 3ul, }; }
      namespace PF8  { enum { EVENTOUT = 15ul,  QUADSPI_BK1_IO0 = 10ul,  TIM13_CH1 = 9ul, }; }
      namespace PF9  { enum { EVENTOUT = 15ul,  QUADSPI_BK1_IO1 = 10ul,  TIM14_CH1 = 9ul, }; }
      namespace PG0  { enum { CAN1_RX = 9ul,  EVENTOUT = 15ul,  FSMC_A10 = 12ul, }; }
      namespace PG1  { enum { CAN1_TX = 9ul,  EVENTOUT = 15ul,  FSMC_A11 = 12ul, }; }
      namespace PG10 { enum { EVENTOUT = 15ul,  FSMC_NE3 = 12ul, }; }
      namespace PG11 { enum { CAN2_RX = 9ul,  EVENTOUT = 15ul, }; }
      namespace PG12 { enum { CAN2_TX = 9ul,  EVENTOUT = 15ul,  FSMC_NE4 = 12ul,  USART6_RTS = 8ul, }; }
      namespace PG13 { enum { EVENTOUT = 15ul,  FSMC_A24 = 12ul,  SYS_TRACED2 = 0ul,  USART6_CTS = 8ul, }; }
      namespace PG14 { enum { EVENTOUT = 15ul,  FSMC_A25 = 12ul,  QUADSPI_BK2_IO3 = 9ul,  SYS_TRACED3 = 0ul,  USART6_TX = 8ul, }; }
      namespace PG15 { enum { EVENTOUT = 15ul,  USART6_CTS = 8ul, }; }
      namespace PG2  { enum { EVENTOUT = 15ul,  FSMC_A12 = 12ul, }; }
      namespace PG3  { enum { EVENTOUT = 15ul,  FSMC_A13 = 12ul, }; }
      namespace PG4  { enum { EVENTOUT = 15ul,  FSMC_A14 = 12ul, }; }
      namespace PG5  { enum { EVENTOUT = 15ul,  FSMC_A15 = 12ul, }; }
      namespace PG6  { enum { EVENTOUT = 15ul,  QUADSPI_BK1_NCS = 10ul, }; }
      namespace PG7  { enum { EVENTOUT = 15ul,  USART6_CK = 8ul, }; }
      namespace PG8  { enum { EVENTOUT = 15ul,  USART6_RTS = 8ul, }; }
      namespace PG9  { enum { EVENTOUT = 15ul,  FSMC_NE2 = 12ul,  QUADSPI_BK2_IO2 = 9ul,  USART6_RX = 8ul, }; }
      namespace PH0  { enum { EVENTOUT = 15ul, }; }
      namespace PH1  { enum { EVENTOUT = 15ul, }; }
    } // namespace Af
  } // inline namespace 
} // namespace mpp::gpio 
 
