/**
  ***********************************************************
  @file   /src/gpio/st/spec/STM32F401_gpio_v1_0.hpp
  @brief  This is autogenerated file        
  ***********************************************************
**/

#pragma once

//____________________INCLUDE_____________________//
#include <cstdint>

#if defined (STM32F401xc)
  #include "stm32f401xc.h"
#elif defined (STM32F401xe)
  #include "stm32f401xe.h"
#else
  #error "You must define supported target"
#endif



namespace mpp::gpio
{
  inline namespace STM32F401_gpio_v1_0
  {
    enum class Port { 
      A = GPIOA_BASE,
      B = GPIOB_BASE,
      C = GPIOC_BASE,
      D = GPIOD_BASE,
      E = GPIOE_BASE,
      H = GPIOH_BASE,
    };

    template< typename IO >
    constexpr bool IsValidIo()
    {
      switch(IO::Port())
      { 
        case Port::A: return IO::Pin() < 16u;
        case Port::B: return IO::Pin() < 16u;
        case Port::C: return IO::Pin() < 16u;
        case Port::D: return IO::Pin() < 16u;
        case Port::E: return IO::Pin() < 16u;
        case Port::H: return IO::Pin() < 2u;

        default: return false;
      }
    }


    

    struct PA0  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 0u; }
      enum { TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  TIM5_CH1 = 2ul,  USART2_CTS = 7ul, }; 
    };

    struct PA1  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 1u; }
      enum { TIM2_CH2 = 1ul,  TIM5_CH2 = 2ul,  USART2_RTS = 7ul, }; 
    };

    struct PA10 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 10u; }
      enum { TIM1_CH3 = 1ul,  USART1_RX = 7ul,  USB_OTG_FS_ID = 10ul, }; 
    };

    struct PA11 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 11u; }
      enum { TIM1_CH4 = 1ul,  USART1_CTS = 7ul,  USART6_TX = 8ul,  USB_OTG_FS_DM = 10ul, }; 
    };

    struct PA12 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 12u; }
      enum { TIM1_ETR = 1ul,  USART1_RTS = 7ul,  USART6_RX = 8ul,  USB_OTG_FS_DP = 10ul, }; 
    };

    struct PA13 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 13u; }
      enum { SYS_JTMS_SWDIO = 0ul, }; 
    };

    struct PA14 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 14u; }
      enum { I2S3ext_WS = 5ul,  SYS_JTCK_SWCLK = 0ul, }; 
    };

    struct PA15 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 15u; }
      enum { I2S3_WS = 6ul,  SPI1_NSS = 5ul,  SPI3_NSS = 6ul,  SYS_JTDI = 0ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul, }; 
    };

    struct PA2  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 2u; }
      enum { TIM2_CH3 = 1ul,  TIM5_CH3 = 2ul,  TIM9_CH1 = 3ul,  USART2_TX = 7ul, }; 
    };

    struct PA3  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 3u; }
      enum { TIM2_CH4 = 1ul,  TIM5_CH4 = 2ul,  TIM9_CH2 = 3ul,  USART2_RX = 7ul, }; 
    };

    struct PA4  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 4u; }
      enum { I2S3_WS = 6ul,  SPI1_NSS = 5ul,  SPI3_NSS = 6ul,  USART2_CK = 7ul, }; 
    };

    struct PA5  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 5u; }
      enum { SPI1_SCK = 5ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul, }; 
    };

    struct PA6  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 6u; }
      enum { SPI1_MISO = 5ul,  TIM1_BKIN = 1ul,  TIM3_CH1 = 2ul, }; 
    };

    struct PA7  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 7u; }
      enum { SPI1_MOSI = 5ul,  TIM1_CH1N = 1ul,  TIM3_CH2 = 2ul, }; 
    };

    struct PA8  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 8u; }
      enum { I2C3_SCL = 4ul,  RCC_MCO_1 = 0ul,  TIM1_CH1 = 1ul,  USART1_CK = 7ul,  USB_OTG_FS_SOF = 10ul, }; 
    };

    struct PA9  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::A; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 9u; }
      enum { I2C3_SMBA = 4ul,  TIM1_CH2 = 1ul,  USART1_TX = 7ul, }; 
    };

    struct PB0  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 0u; }
      enum { TIM1_CH2N = 1ul,  TIM3_CH3 = 2ul, }; 
    };

    struct PB1  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 1u; }
      enum { TIM1_CH3N = 1ul,  TIM3_CH4 = 2ul, }; 
    };

    struct PB10 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 10u; }
      enum { I2C2_SCL = 4ul,  I2S2_CK = 5ul,  SPI2_SCK = 5ul,  TIM2_CH3 = 1ul, }; 
    };

    struct PB11 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 11u; }
      enum { I2C2_SDA = 4ul,  TIM2_CH4 = 1ul, }; 
    };

    struct PB12 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 12u; }
      enum { I2C2_SMBA = 4ul,  I2S2_WS = 5ul,  I2S2ext_WS = 6ul,  SPI2_NSS = 5ul,  TIM1_BKIN = 1ul, }; 
    };

    struct PB13 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 13u; }
      enum { I2S2_CK = 5ul,  I2S2ext_CK = 6ul,  SPI2_SCK = 5ul,  TIM1_CH1N = 1ul, }; 
    };

    struct PB14 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 14u; }
      enum { I2S2_ext_SD = 6ul,  SPI2_MISO = 5ul,  TIM1_CH2N = 1ul, }; 
    };

    struct PB15 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 15u; }
      enum { I2S2_SD = 5ul,  I2S2ext_MISO = 6ul,  RTC_REFIN = 0ul,  SPI2_MOSI = 5ul,  TIM1_CH3N = 1ul, }; 
    };

    struct PB2  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 2u; }
      enum {}; 
    };

    struct PB3  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 3u; }
      enum { I2C2_SDA = 9ul,  I2S3_CK = 6ul,  SPI1_SCK = 5ul,  SPI3_SCK = 6ul,  SYS_JTDO_SWO = 0ul,  TIM2_CH2 = 1ul, }; 
    };

    struct PB4  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 4u; }
      enum { I2C3_SDA = 9ul,  I2S3_ext_SD = 7ul,  SPI1_MISO = 5ul,  SPI3_MISO = 6ul,  SYS_JTRST = 0ul,  TIM3_CH1 = 2ul, }; 
    };

    struct PB5  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 5u; }
      enum { I2C1_SMBA = 4ul,  I2S3_SD = 6ul,  SPI1_MOSI = 5ul,  SPI3_MOSI = 6ul,  TIM3_CH2 = 2ul, }; 
    };

    struct PB6  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 6u; }
      enum { I2C1_SCL = 4ul,  TIM4_CH1 = 2ul,  USART1_TX = 7ul, }; 
    };

    struct PB7  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 7u; }
      enum { I2C1_SDA = 4ul,  TIM4_CH2 = 2ul,  USART1_RX = 7ul, }; 
    };

    struct PB8  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 8u; }
      enum { I2C1_SCL = 4ul,  SDIO_D4 = 12ul,  TIM10_CH1 = 3ul,  TIM4_CH3 = 2ul, }; 
    };

    struct PB9  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::B; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 9u; }
      enum { I2C1_SDA = 4ul,  I2S2_WS = 5ul,  SDIO_D5 = 12ul,  SPI2_NSS = 5ul,  TIM11_CH1 = 3ul,  TIM4_CH4 = 2ul, }; 
    };

    struct PC0  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 0u; }
      enum {}; 
    };

    struct PC1  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 1u; }
      enum {}; 
    };

    struct PC10 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 10u; }
      enum { I2S3_CK = 6ul,  I2S3ext_CK = 5ul,  SDIO_D2 = 12ul,  SPI3_SCK = 6ul, }; 
    };

    struct PC11 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 11u; }
      enum { I2S3_ext_SD = 5ul,  SDIO_D3 = 12ul,  SPI3_MISO = 6ul, }; 
    };

    struct PC12 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 12u; }
      enum { I2S3_SD = 6ul,  I2S3ext_MISO = 5ul,  SDIO_CK = 12ul,  SPI3_MOSI = 6ul, }; 
    };

    struct PC13 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 13u; }
      enum {}; 
    };

    struct PC14 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 14u; }
      enum {}; 
    };

    struct PC15 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 15u; }
      enum {}; 
    };

    struct PC2  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 2u; }
      enum { I2S2_ext_SD = 6ul,  SPI2_MISO = 5ul, }; 
    };

    struct PC3  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 3u; }
      enum { I2S2_SD = 5ul,  SPI2_MOSI = 5ul, }; 
    };

    struct PC4  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 4u; }
      enum {}; 
    };

    struct PC5  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 5u; }
      enum {}; 
    };

    struct PC6  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 6u; }
      enum { I2S2_MCK = 5ul,  SDIO_D6 = 12ul,  TIM3_CH1 = 2ul,  USART6_TX = 8ul, }; 
    };

    struct PC7  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 7u; }
      enum { I2S3_MCK = 6ul,  SDIO_D7 = 12ul,  TIM3_CH2 = 2ul,  USART6_RX = 8ul, }; 
    };

    struct PC8  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 8u; }
      enum { SDIO_D0 = 12ul,  TIM3_CH3 = 2ul,  USART6_CK = 8ul, }; 
    };

    struct PC9  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::C; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 9u; }
      enum { I2C3_SDA = 4ul,  I2S_CKIN = 5ul,  RCC_MCO_2 = 0ul,  SDIO_D1 = 12ul,  TIM3_CH4 = 2ul, }; 
    };

    struct PD0  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 0u; }
      enum {}; 
    };

    struct PD1  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 1u; }
      enum {}; 
    };

    struct PD10 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 10u; }
      enum {}; 
    };

    struct PD11 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 11u; }
      enum {}; 
    };

    struct PD12 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 12u; }
      enum { TIM4_CH1 = 2ul, }; 
    };

    struct PD13 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 13u; }
      enum { TIM4_CH2 = 2ul, }; 
    };

    struct PD14 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 14u; }
      enum { TIM4_CH3 = 2ul, }; 
    };

    struct PD15 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 15u; }
      enum { TIM4_CH4 = 2ul, }; 
    };

    struct PD2  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 2u; }
      enum { SDIO_CMD = 12ul,  TIM3_ETR = 2ul, }; 
    };

    struct PD3  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 3u; }
      enum { I2S2_CK = 5ul,  SPI2_SCK = 5ul,  USART2_CTS = 7ul, }; 
    };

    struct PD4  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 4u; }
      enum { USART2_RTS = 7ul, }; 
    };

    struct PD5  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 5u; }
      enum { USART2_TX = 7ul, }; 
    };

    struct PD6  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 6u; }
      enum { I2S3_SD = 5ul,  SPI3_MOSI = 5ul,  USART2_RX = 7ul, }; 
    };

    struct PD7  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 7u; }
      enum { USART2_CK = 7ul, }; 
    };

    struct PD8  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 8u; }
      enum {}; 
    };

    struct PD9  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::D; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 9u; }
      enum {}; 
    };

    struct PE0  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 0u; }
      enum { TIM4_ETR = 2ul, }; 
    };

    struct PE1  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 1u; }
      enum {}; 
    };

    struct PE10 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 10u; }
      enum { TIM1_CH2N = 1ul, }; 
    };

    struct PE11 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 11u; }
      enum { SPI4_NSS = 5ul,  TIM1_CH2 = 1ul, }; 
    };

    struct PE12 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 12u; }
      enum { SPI4_SCK = 5ul,  TIM1_CH3N = 1ul, }; 
    };

    struct PE13 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 13u; }
      enum { SPI4_MISO = 5ul,  TIM1_CH3 = 1ul, }; 
    };

    struct PE14 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 14u; }
      enum { SPI4_MOSI = 5ul,  TIM1_CH4 = 1ul, }; 
    };

    struct PE15 
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 15u; }
      enum { TIM1_BKIN = 1ul, }; 
    };

    struct PE2  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 2u; }
      enum { SPI4_SCK = 5ul,  SYS_TRACECLK = 0ul, }; 
    };

    struct PE3  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 3u; }
      enum { SYS_TRACED0 = 0ul, }; 
    };

    struct PE4  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 4u; }
      enum { SPI4_NSS = 5ul,  SYS_TRACED1 = 0ul, }; 
    };

    struct PE5  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 5u; }
      enum { SPI4_MISO = 5ul,  SYS_TRACED2 = 0ul,  TIM9_CH1 = 3ul, }; 
    };

    struct PE6  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 6u; }
      enum { SPI4_MOSI = 5ul,  SYS_TRACED3 = 0ul,  TIM9_CH2 = 3ul, }; 
    };

    struct PE7  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 7u; }
      enum { TIM1_ETR = 1ul, }; 
    };

    struct PE8  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 8u; }
      enum { TIM1_CH1N = 1ul, }; 
    };

    struct PE9  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::E; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 9u; }
      enum { TIM1_CH1 = 1ul, }; 
    };

    struct PH0  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::H; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 0u; }
      enum {}; 
    };

    struct PH1  
    {
      constexpr inline static auto const Port() noexcept(true) { return Port::H; }
	  constexpr inline static std::uint32_t const Pin()  noexcept(true) { return 1u; }
      enum {}; 
    };
    
  } // inline namespace 
} // namespace mpp::gpio 
 
