/**
  ***********************************************************
  @file   /src/flash/st/spec/stm32f407_flash.hpp
  @brief  This is autogenerated file        
  ***********************************************************
**/

#pragma once


//____________________INCLUDE_____________________//
#include <cstdint>

#if defined (STM32F405xx)
  #include "stm32f405xx.h"
#elif defined (STM32F407xx)
  #include "stm32f407xx.h"
#elif defined (STM32F415xx)
  #include "stm32f415xx.h"
#elif defined (STM32F417xx)
  #include "stm32f417xx.h"
#elif defined (STM32F427xx)
  #include "stm32f427xx.h"
#elif defined (STM32F429xx)
  #include "stm32f429xx.h"
#elif defined (STM32F437xx)
  #include "stm32f437xx.h"
#elif defined (STM32F439xx)
  #include "stm32f439xx.h"
#elif defined (STM32F446xx)
  #include "stm32f446xx.h"
#elif defined (STM32F469xx)
  #include "stm32f469xx.h"
#elif defined (STM32F479xx)
  #include "stm32f479xx.h"
#else
  #error "You must define supported target"
#endif

 


namespace mpp::flash
{
  inline namespace stm32f407xx
  {
    constexpr std::uint32_t kFlashMaxSectorInBank = 12u;
    constexpr std::uint32_t kFlashWaitStateMax = 15u;
      
    constexpr std::uint32_t GetWaitState( std::uint32_t ClockHz , float VoltageMin ) noexcept ( true )
    {
      std::uint32_t ws = kFlashWaitStateMax;
        
      if constexpr ( VoltageMin < 2.1f )
        ws = ClockHz / 20'000'001ul;
      else 
        if constexpr ( VoltageMin < 2.4f )
          ws = ClockHz / 22'000'001ul;
        else
          if constexpr ( VoltageMin < 2.7f )
            ws = ClockHz / 24'000'001ul;
          else
              ws = ClockHz / 30'000'001ul;
        
      return ws > kFlashWaitStateMax ? kFlashWaitStateMax : ws;   
    }
      
    
      
  }  // inline namespace
}  // namespace mpp::flash


